export enum RevenueModel {
    PAY_PER_LEAD = "PAY_PER_LEAD",
    PAY_PER_INQUIRY = "PAY_PER_INQUIRY",
    PAY_PER_SALE = "PAY_PER_SALE",
    PAY_PER_CLICK = "PAY_PER_CLICK",
    PAY_PER_INSTALL = "PAY_PER_INSTALL"
}

export enum MediaPropertyType {
    WEBSITE = "WEBSITE",
    MOBILE = "MOBILE",
    SOCIAL = "SOCIAL"
}

export enum MobilePlatform {
    IOS = "IOS",
    ANDROID = "ANDROID"
}

export enum Installs {
    HUNDRED_PLUS = "HUNDRED_PLUS",
    THOUSAND_PLUS = "THOUSAND_PLUS",
    TEN_THOUSAND_PLUS = "TEN_THOUSAND_PLUS",
    HUNDRED_THOUSAND_PLUS = "HUNDRED_THOUSAND_PLUS",
    MILLION_PLUS = "MILLION_PLUS",
    TEN_MILLION_PLUS = "TEN_MILLION_PLUS",
    HUNDRED_MILLION_PLUS = "HUNDRED_MILLION_PLUS"
}
export enum SocialPlatform {
    FACEBOOK = "FACEBOOK",
    TWITTER = "TWITTER",
    INSTAGRAM = "INSTAGRAM",
    PINTEREST = "PINTEREST"
}

export enum Followers {
    HUNDRED_PLUS = "HUNDRED_PLUS",
    THOUSAND_PLUS = "THOUSAND_PLUS",
    TEN_THOUSAND_PLUS = "TEN_THOUSAND_PLUS",
    HUNDRED_THOUSAND_PLUS = "HUNDRED_THOUSAND_PLUS",
    MILLION_PLUS = "MILLION_PLUS",
    TEN_MILLION_PLUS = "TEN_MILLION_PLUS",
    HUNDRED_MILLION_PLUS = "HUNDRED_MILLION_PLUS"
}
