import type { Metadata } from "next";
import "@/styles/index.scss";
import { Toaster } from "react-hot-toast";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Media Properties",
    description: "Generated by create next app",
};

export default function MediaPropertiesLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Suspense>
                {children}
                <Toaster
                    position="bottom-right"
                    toastOptions={{ duration: 1500 }}
                />
            </Suspense>
        </>
    );
}
