import type { Metadata } from "next";
import "@/styles/index.scss";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Users",
    description: "Generated by create next app",
};

export default function UsersLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <Suspense>{children}</Suspense>;
}
