export const partnerCreativeMockData = [
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },

  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
  {
    campaignName: "Campaign Name",
    campaignId: "",
    banner: "0",
    textLink: "10",
    feed: "0",
    html: "90",
    htmlForm: "0",
    email: "90",
  },
];
