export const compaignData = [
  {
    AdvertiserId: "1217855",
    AdvertiserName: "LightInTheBoxLimited",
    AdvertiserUrl: "http://www.eechic.com",
    CampaignId: "17561",
    CampaignName: "Punktrendy",
    CampaignUrl: "https://punktrendy.com",
    CampaignDescription:
      "PunkTrendy Is An Upcoming Brand About To Make Waves Within The Fashion Industry For Men Clothing",
    ShippingRegions: ["SOUTHAFRICA", "UK", "US"],
    CampaignLogoUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Logo",
    PublicTermsUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/PublicTerms",
    ContractStatus: "Active",
    ContractUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Contracts/Active",
    TrackingLink: "https://punktrendy.pxf.io/c/3293666/1488088/17561",
    AllowsDeeplinking: "true",
    DeeplinkDomains: ["SOUTHAFRICA", "UK", "US"],
    Uri: "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561",
  },
  {
    AdvertiserId: "1217855",
    AdvertiserName: "LightInTheBoxLimited",
    AdvertiserUrl: "http://www.eechic.com",
    CampaignId: "17561",
    CampaignName: "Punktrendy",
    CampaignUrl: "https://punktrendy.com",
    CampaignDescription:
      "PunkTrendy Is An Upcoming Brand About To Make Waves Within The Fashion Industry For Men Clothing",
    ShippingRegions: ["SOUTHAFRICA", "UK", "US"],
    CampaignLogoUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Logo",
    PublicTermsUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/PublicTerms",
    ContractStatus: "Active",
    ContractUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Contracts/Active",
    TrackingLink: "https://punktrendy.pxf.io/c/3293666/1488088/17561",
    AllowsDeeplinking: "true",
    DeeplinkDomains: ["SOUTHAFRICA", "UK", "US"],
    Uri: "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561",
  },
  {
    AdvertiserId: "1217855",
    AdvertiserName: "LightInTheBoxLimited",
    AdvertiserUrl: "http://www.eechic.com",
    CampaignId: "17561",
    CampaignName: "Punktrendy",
    CampaignUrl: "https://punktrendy.com",
    CampaignDescription:
      "PunkTrendy Is An Upcoming Brand About To Make Waves Within The Fashion Industry For Men Clothing",
    ShippingRegions: ["SOUTHAFRICA", "UK", "US"],
    CampaignLogoUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Logo",
    PublicTermsUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/PublicTerms",
    ContractStatus: "Active",
    ContractUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Contracts/Active",
    TrackingLink: "https://punktrendy.pxf.io/c/3293666/1488088/17561",
    AllowsDeeplinking: "true",
    DeeplinkDomains: [
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
      "UK",
      "US",
    ],
    Uri: "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561",
  },
  {
    AdvertiserId: "1217855",
    AdvertiserName: "LightInTheBoxLimited",
    AdvertiserUrl: "http://www.eechic.com",
    CampaignId: "17561",
    CampaignName: "Punktrendy",
    CampaignUrl: "https://punktrendy.com",
    CampaignDescription:
      "PunkTrendy Is An Upcoming Brand About To Make Waves Within The Fashion Industry For Men Clothing",
    ShippingRegions: ["SOUTHAFRICA", "UK", "US"],
    CampaignLogoUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Logo",
    PublicTermsUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/PublicTerms",
    ContractStatus: "Active",
    ContractUri:
      "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561/Contracts/Active",
    TrackingLink: "https://punktrendy.pxf.io/c/3293666/1488088/17561",
    AllowsDeeplinking: "true",
    DeeplinkDomains: ["SOUTHAFRICA", "UK", "US"],
    Uri: "/Mediapartners/IRHNMc2jhm2F3293666Q4hLBJG8y2mYpy1/Campaigns/17561",
  },
];
