import type { Metadata } from "next";
import "@/styles/index.scss";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Click Details",
    description: "Generated by create next app",
};

export default function ClickDetailsLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Suspense>{children}</Suspense>
        </>
    );
}
