import type { Metadata } from "next";
import "@/styles/index.scss";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Programs",
  description: "Generated by create next app",
};

export default function ProgramLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      {children}
      <Toaster position="bottom-left" toastOptions={{ duration: 1500 }} />
    </div>
  );
}
