export const storeItemSampleData = [
  {
    Id: "product_1000_9876543",
    CatalogId: "1000",
    CampaignId: "1234",
    CampaignName: "Acme Partner Program",
    CatalogItemId: "9876543",
    Name: "Acme Tennis Balls (One Dozen)",
    Description: "A case of one dozen professional-grade tennis balls.",
    MultiPack: "",
    Bullets: [],
    Labels: [],
    Manufacturer: "",
    Url: "https://example.com/shop/tennis-balls",
    MobileUrl: "",
    ImageUrl: "https://example.com/shop/tennis-balls/tennis-balls.png",
    ProductBid: "",
    AdditionalImageUrls: [],
    CurrentPrice: "16.99",
    OriginalPrice: "16.99",
    DiscountPercentage: "",
    Currency: "USD",
    StockAvailability: "InStock",
    EstimatedShipDate: "",
    LaunchDate: "",
    ExpirationDate: "",
    Gtin: "",
    GtinType: "",
    Asin: "",
    Mpn: "",
    ShippingRate: "",
    ShippingWeight: "",
    ShippingWeightUnit: "",
    ShippingLength: "",
    ShippingWidth: "",
    ShippingHeight: "",
    ShippingLengthUnit: "",
    ShippingLabel: "",
    Category: "Home > Sports",
    SubCategory: "Home > Sports > Tennis & Golf",
    AdvertiserFormatCategories: "",
    OriginalFormatCategory: "",
    OriginalFormatCategoryId: "",
    ParentName: "",
    ParentSku: "",
    IsParent: false,
    ItemGroupId: "AB12345",
    Colors: [],
    Material: "",
    Pattern: "",
    Size: "",
    SizeUnit: "",
    Weight: "",
    WeightUnit: "",
    Condition: "New",
    AgeGroup: "",
    AgeRangeMin: "0",
    AgeRangeMax: "0",
    AgeRangeUnit: "",
    Gender: "",
    Adult: false,
    Text1: "",
    Text2: "",
    Text3: "",
    Numeric1: "",
    Numeric2: "",
    Numeric3: "",
    Money1: "",
    Money2: "",
    Money3: "",
    Uri: "/Mediapartners/<AccountSID>/Catalogs/1000/Items/product_100_9876543",
  },
  {
    Id: "product_1000_9876543",
    CatalogId: "1000",
    CampaignId: "1234",
    CampaignName: "Acme Partner Program",
    CatalogItemId: "9876543",
    Name: "Acme Tennis Balls (One Dozen)",
    Description: "A case of one dozen professional-grade tennis balls.",
    MultiPack: "",
    Bullets: [],
    Labels: [],
    Manufacturer: "",
    Url: "https://example.com/shop/tennis-balls",
    MobileUrl: "",
    ImageUrl: "https://example.com/shop/tennis-balls/tennis-balls.png",
    ProductBid: "",
    AdditionalImageUrls: [],
    CurrentPrice: "16.99",
    OriginalPrice: "16.99",
    DiscountPercentage: "",
    Currency: "USD",
    StockAvailability: "InStock",
    EstimatedShipDate: "",
    LaunchDate: "",
    ExpirationDate: "",
    Gtin: "",
    GtinType: "",
    Asin: "",
    Mpn: "",
    ShippingRate: "",
    ShippingWeight: "",
    ShippingWeightUnit: "",
    ShippingLength: "",
    ShippingWidth: "",
    ShippingHeight: "",
    ShippingLengthUnit: "",
    ShippingLabel: "",
    Category: "Home > Sports",
    SubCategory: "Home > Sports > Tennis & Golf",
    AdvertiserFormatCategories: "",
    OriginalFormatCategory: "",
    OriginalFormatCategoryId: "",
    ParentName: "",
    ParentSku: "",
    IsParent: false,
    ItemGroupId: "AB12345",
    Colors: [],
    Material: "",
    Pattern: "",
    Size: "",
    SizeUnit: "",
    Weight: "",
    WeightUnit: "",
    Condition: "New",
    AgeGroup: "",
    AgeRangeMin: "0",
    AgeRangeMax: "0",
    AgeRangeUnit: "",
    Gender: "",
    Adult: false,
    Text1: "",
    Text2: "",
    Text3: "",
    Numeric1: "",
    Numeric2: "",
    Numeric3: "",
    Money1: "",
    Money2: "",
    Money3: "",
    Uri: "/Mediapartners/<AccountSID>/Catalogs/1000/Items/product_100_9876543",
  },
  {
    Id: "product_1000_9876543",
    CatalogId: "1000",
    CampaignId: "1234",
    CampaignName: "Acme Partner Program",
    CatalogItemId: "9876543",
    Name: "Acme Tennis Balls (One Dozen)",
    Description: "A case of one dozen professional-grade tennis balls.",
    MultiPack: "",
    Bullets: [],
    Labels: [],
    Manufacturer: "",
    Url: "https://example.com/shop/tennis-balls",
    MobileUrl: "",
    ImageUrl: "https://example.com/shop/tennis-balls/tennis-balls.png",
    ProductBid: "",
    AdditionalImageUrls: [],
    CurrentPrice: "16.99",
    OriginalPrice: "16.99",
    DiscountPercentage: "",
    Currency: "USD",
    StockAvailability: "InStock",
    EstimatedShipDate: "",
    LaunchDate: "",
    ExpirationDate: "",
    Gtin: "",
    GtinType: "",
    Asin: "",
    Mpn: "",
    ShippingRate: "",
    ShippingWeight: "",
    ShippingWeightUnit: "",
    ShippingLength: "",
    ShippingWidth: "",
    ShippingHeight: "",
    ShippingLengthUnit: "",
    ShippingLabel: "",
    Category: "Home > Sports",
    SubCategory: "Home > Sports > Tennis & Golf",
    AdvertiserFormatCategories: "",
    OriginalFormatCategory: "",
    OriginalFormatCategoryId: "",
    ParentName: "",
    ParentSku: "",
    IsParent: false,
    ItemGroupId: "AB12345",
    Colors: [],
    Material: "",
    Pattern: "",
    Size: "",
    SizeUnit: "",
    Weight: "",
    WeightUnit: "",
    Condition: "New",
    AgeGroup: "",
    AgeRangeMin: "0",
    AgeRangeMax: "0",
    AgeRangeUnit: "",
    Gender: "",
    Adult: false,
    Text1: "",
    Text2: "",
    Text3: "",
    Numeric1: "",
    Numeric2: "",
    Numeric3: "",
    Money1: "",
    Money2: "",
    Money3: "",
    Uri: "/Mediapartners/<AccountSID>/Catalogs/1000/Items/product_100_9876543",
  },
  {
    Id: "product_1000_9876543",
    CatalogId: "1000",
    CampaignId: "1234",
    CampaignName: "Acme Partner Program",
    CatalogItemId: "9876543",
    Name: "Acme Tennis Balls (One Dozen)",
    Description: "A case of one dozen professional-grade tennis balls.",
    MultiPack: "",
    Bullets: [],
    Labels: [],
    Manufacturer: "",
    Url: "https://example.com/shop/tennis-balls",
    MobileUrl: "",
    ImageUrl: "https://example.com/shop/tennis-balls/tennis-balls.png",
    ProductBid: "",
    AdditionalImageUrls: [],
    CurrentPrice: "16.99",
    OriginalPrice: "16.99",
    DiscountPercentage: "",
    Currency: "USD",
    StockAvailability: "InStock",
    EstimatedShipDate: "",
    LaunchDate: "",
    ExpirationDate: "",
    Gtin: "",
    GtinType: "",
    Asin: "",
    Mpn: "",
    ShippingRate: "",
    ShippingWeight: "",
    ShippingWeightUnit: "",
    ShippingLength: "",
    ShippingWidth: "",
    ShippingHeight: "",
    ShippingLengthUnit: "",
    ShippingLabel: "",
    Category: "Home > Sports",
    SubCategory: "Home > Sports > Tennis & Golf",
    AdvertiserFormatCategories: "",
    OriginalFormatCategory: "",
    OriginalFormatCategoryId: "",
    ParentName: "",
    ParentSku: "",
    IsParent: false,
    ItemGroupId: "AB12345",
    Colors: [],
    Material: "",
    Pattern: "",
    Size: "",
    SizeUnit: "",
    Weight: "",
    WeightUnit: "",
    Condition: "New",
    AgeGroup: "",
    AgeRangeMin: "0",
    AgeRangeMax: "0",
    AgeRangeUnit: "",
    Gender: "",
    Adult: false,
    Text1: "",
    Text2: "",
    Text3: "",
    Numeric1: "",
    Numeric2: "",
    Numeric3: "",
    Money1: "",
    Money2: "",
    Money3: "",
    Uri: "/Mediapartners/<AccountSID>/Catalogs/1000/Items/product_100_9876543",
  },
  {
    Id: "product_1000_9876543",
    CatalogId: "1000",
    CampaignId: "1234",
    CampaignName: "Acme Partner Program",
    CatalogItemId: "9876543",
    Name: "Acme Tennis Balls (One Dozen)",
    Description: "A case of one dozen professional-grade tennis balls.",
    MultiPack: "",
    Bullets: [],
    Labels: [],
    Manufacturer: "",
    Url: "https://example.com/shop/tennis-balls",
    MobileUrl: "",
    ImageUrl: "https://example.com/shop/tennis-balls/tennis-balls.png",
    ProductBid: "",
    AdditionalImageUrls: [],
    CurrentPrice: "16.99",
    OriginalPrice: "16.99",
    DiscountPercentage: "",
    Currency: "USD",
    StockAvailability: "InStock",
    EstimatedShipDate: "",
    LaunchDate: "",
    ExpirationDate: "",
    Gtin: "",
    GtinType: "",
    Asin: "",
    Mpn: "",
    ShippingRate: "",
    ShippingWeight: "",
    ShippingWeightUnit: "",
    ShippingLength: "",
    ShippingWidth: "",
    ShippingHeight: "",
    ShippingLengthUnit: "",
    ShippingLabel: "",
    Category: "Home > Sports",
    SubCategory: "Home > Sports > Tennis & Golf",
    AdvertiserFormatCategories: "",
    OriginalFormatCategory: "",
    OriginalFormatCategoryId: "",
    ParentName: "",
    ParentSku: "",
    IsParent: false,
    ItemGroupId: "AB12345",
    Colors: [],
    Material: "",
    Pattern: "",
    Size: "",
    SizeUnit: "",
    Weight: "",
    WeightUnit: "",
    Condition: "New",
    AgeGroup: "",
    AgeRangeMin: "0",
    AgeRangeMax: "0",
    AgeRangeUnit: "",
    Gender: "",
    Adult: false,
    Text1: "",
    Text2: "",
    Text3: "",
    Numeric1: "",
    Numeric2: "",
    Numeric3: "",
    Money1: "",
    Money2: "",
    Money3: "",
    Uri: "/Mediapartners/<AccountSID>/Catalogs/1000/Items/product_100_9876543",
  },
  {
    Id: "product_1000_9876543",
    CatalogId: "1000",
    CampaignId: "1234",
    CampaignName: "Acme Partner Program",
    CatalogItemId: "9876543",
    Name: "Acme Tennis Balls (One Dozen)",
    Description: "A case of one dozen professional-grade tennis balls.",
    MultiPack: "",
    Bullets: [],
    Labels: [],
    Manufacturer: "",
    Url: "https://example.com/shop/tennis-balls",
    MobileUrl: "",
    ImageUrl: "https://example.com/shop/tennis-balls/tennis-balls.png",
    ProductBid: "",
    AdditionalImageUrls: [],
    CurrentPrice: "16.99",
    OriginalPrice: "16.99",
    DiscountPercentage: "",
    Currency: "USD",
    StockAvailability: "InStock",
    EstimatedShipDate: "",
    LaunchDate: "",
    ExpirationDate: "",
    Gtin: "",
    GtinType: "",
    Asin: "",
    Mpn: "",
    ShippingRate: "",
    ShippingWeight: "",
    ShippingWeightUnit: "",
    ShippingLength: "",
    ShippingWidth: "",
    ShippingHeight: "",
    ShippingLengthUnit: "",
    ShippingLabel: "",
    Category: "Home > Sports",
    SubCategory: "Home > Sports > Tennis & Golf",
    AdvertiserFormatCategories: "",
    OriginalFormatCategory: "",
    OriginalFormatCategoryId: "",
    ParentName: "",
    ParentSku: "",
    IsParent: false,
    ItemGroupId: "AB12345",
    Colors: [],
    Material: "",
    Pattern: "",
    Size: "",
    SizeUnit: "",
    Weight: "",
    WeightUnit: "",
    Condition: "New",
    AgeGroup: "",
    AgeRangeMin: "0",
    AgeRangeMax: "0",
    AgeRangeUnit: "",
    Gender: "",
    Adult: false,
    Text1: "",
    Text2: "",
    Text3: "",
    Numeric1: "",
    Numeric2: "",
    Numeric3: "",
    Money1: "",
    Money2: "",
    Money3: "",
    Uri: "/Mediapartners/<AccountSID>/Catalogs/1000/Items/product_100_9876543",
  },
];
